version: '3.3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: therong187
      MSQL_DATABASE: opencord
    ports:
      - 3306:3306

volumes:
  mysql-data:
